### ISSUE TITLE
Bug in GeocodeingClient

### ISSUE THREAD

**Issue by kamilzamerski** [2amigos/yii2-google-maps-library#16]
GeocodingClient.php:74 you check if param address is null OR param components is null, but in exception you write '"address" or "components" must be set for the request.'

In my opinion, you should change 74 line from:
<code>if ($this->params['address'] == null <b><u>||</u></b> $this->params['components'] == null) {</code>
to:
<code>if ($this->params['address'] == null <b><u>&&</u></b> $this->params['components'] == null) {</code>

**Comment by cloudeeo** [comment]
Just found the same issue, the exception thrown says that "address" OR "components" must be set, not both.
