### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Faryshta** [2amigos/yii2-google-maps-library#19]
is it possible to use this on forms?

I want to obtain the coordinates of a building by searching on google maps then saving it on my database

**Comment by petrabarus** [comment]
As far as I know, you still have to create a widget based on `InputWidget` class. I've created one myself for my personal project.

**Comment by Faryshta** [comment]
Thanks, any guidelines on how to do it? I am pretty much new to google maps api.

**Comment by tonydspaniard** [comment]
I did it in the past with Yii1 version: https://github.com/tonydspaniard/egmap/blob/master/EGMapGeocodeTool.php 

Maybe you can get some hints
