### ISSUE TITLE
Class 'dosamigos\google\maps\Map' not found

### ISSUE THREAD

**Issue by timmy78** [2amigos/yii2-google-maps-library#20]
Hi
I correctly installed the extension via composer.
But when use it : ```Class 'dosamigos\google\maps\Map' not found```
```
$map = new dosamigos\google\maps\Map([
        'center' => $coord,
        'zoom' => 14
    ]);
```
I don't know why, it's not the first extension that I install :/
The last time I had this error, it was when I installed  [this extension](https://github.com/petrabarus/yii2-googleplacesautocomplete)

Thank you !

**Comment by tonydspaniard** [comment]
Strange... namespaces are correct: https://github.com/2amigos/yii2-google-maps-library/blob/master/Map.php#L7

I need to revisit the extension as we are refactoring all of them to suit our new standards: http://yiiwheels.com. When I do it, will check it.

**Comment by timmy78** [comment]
Yes it is strange. And this error appends for all the extension classes.

However I have the classes in vendor/2amigos/yii2-google-maps-library

Question : I have saved locations whith Google Places. How can I define a Marker with an address ?

Thanks

**Comment by tonydspaniard** [comment]
@timmy78 you need to use https://github.com/2amigos/yii2-google-maps-library/blob/master/Map.php#L7 that will return the geo information if as an "string address", check the url pointed on the method. 

Once, you have the lat, lng, then you just need to add a marker as explained on https://github.com/2amigos/yii2-google-maps-library/blob/master/Map.php#L7

**Comment by timmy78** [comment]
@tonydspaniard Did you paste the good URLs ? ^^

**Comment by timmy78** [comment]
Ok I think I found what I would : http://code.tutsplus.com/tutorials/building-your-startup-with-php-geolocation-and-google-places--cms-22729
GeocodingClient

=)

**Comment by tonydspaniard** [comment]
@timmy78 updated :)
