### ISSUE TITLE
Custom style for InfoWindow

### ISSUE THREAD

**Issue by elorian** [2amigos/yii2-google-maps-library#22]
Hi!
I not found style options in InfoWindow class, but google map have InfoBox class (http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.5/docs/reference.html#InfoBox) with custom styles.

I don't know how use/add this class in your extension, can you help me?
Thank you!

**Comment by WadeShuler** [comment]
Here is an example of how I styled them. Please note, my model returns an array of results, I loop through them, and create a marker for each one. You will need to replace it with your own code.

    $providers = BenefitProvider::find()->all();

    foreach( $providers as $provider) {

        $marker = new Marker([
            'position' => new LatLng(['lat' => $provider->address_latitude, 'lng' => $provider->address_longitude]),
            'title' => $provider->name,
            'icon' => 'path/to/icon.png',
        ]);

        // bootstrap in marker info
        $html = '
            <div class="container" style="width:400px;max-width:400px;">
                <div class="row">
                    <div class="col-sm-3"><img src="' . $provider->benefit->logo . '" width="75" height="75" /></div>
                    <div class="col-sm-7">
                        <h3 style="font-size:14px;margin-top:0;margin-bottom:5px;">' . $provider->name . '</h3>
                        <p style="font-size:11px;text-align:justify;">' . $provider->description . '</p>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div class="col-sm-6" style="text-align:center;"><a class="btn btn-brcustom btn-brgreen btn-lg" style="margin:5px auto;width:150px!important;height:auto!important;" href="' . Url::toRoute(['benefit/view', 'id'=>$provider->benefit_id]) . '">VIEW BENEFIT</a></div>
                    <div class="col-sm-6" style="text-align:center;"><a class="btn btn-brcustom btn-brblack btn-lg" style="margin:5px auto;width:150px!important;height:auto!important;" href="' . $provider->website . '">GET STARTED</a></div>
                </div>
            </div>
        ';

        // Provide a shared InfoWindow to the marker
        $marker->attachInfoWindow(
            new InfoWindow([
                'content' => $html,
            ])
        );

        // Add marker to the map
        $map->addOverlay($marker);

    }

**Comment by tonydspaniard** [comment]
Thanks @WadeShuler
