### ISSUE TITLE
GeocodingClient has logic OR bug in lookup()

### ISSUE THREAD

**Issue by dhiraj** [2amigos/yii2-google-maps-library#28]
The '*or*' in the below if:

        if ($this->params['address'] == null || $this->params['components'] == null) {
            throw new InvalidConfigException('"address" or "components" must be set for the request. Both cannot be null');
        }

should actually be an '*and*':

        if ($this->params['address'] == null && $this->params['components'] == null) {
            throw new InvalidConfigException('"address" or "components" must be set for the request. Both cannot be null');
        }

**Comment by tonydspaniard** [comment]
Do you have time for a pr?

**Comment by tonydspaniard** [comment]
@dhiraj this was already fixed: https://github.com/2amigos/yii2-google-maps-library/blob/master/services/GeocodingClient.php#L74
