### ISSUE TITLE
GeocodingClient does not construct with address in array parameter

### ISSUE THREAD

**Issue by dhiraj** [2amigos/yii2-google-maps-library#29]
When attempting to construct a Geocoding client with what looks like the recommended way of passing 'address'=>'an addressstring in constructor Yii throws `UnknownProperty` exception.

`new GeocodingClient(['address' => $sAddress])`

**Comment by tonydspaniard** [comment]
should be: 

```php 
new GeocodingClient(['params' => ['address' => $sAddress]]);
```
