### ISSUE TITLE
Problems with extension in a modal window rendered via Ajax

### ISSUE THREAD

**Issue by reuhtte** [2amigos/yii2-google-maps-library#34]
Error 

Uncaught ReferenceError: google is not defined

js?key=SomeKey&libraries=3.1.18&language=en&_=1441313318502:8 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

===

View rendered via AJAX
```
<?php

use dosamigos\google\maps\LatLng;
use dosamigos\google\maps\Map;

/* @var $this yii\web\View */

$coord = new LatLng(['lat' => 39.720089311812094, 'lng' => 2.91165944519042]);
$map = new Map([
    'center' => $coord,
    'zoom' => 14,
]);

// Display the map -finally :)
echo $map->display();
```
===

Modal Code in the Main View

... Some detailView attribute
```
'attribute' => 'gps',
'format' => 'raw',
'value' => Html::a(Html::tag('i', '', ['class' => 'icon fa fa-map',]),null,[
    'data-toggle' => 'modal',
    'data-target' => '#show-map-modal',
    'data-url' => \yii\helpers\Url::to(['show-map', 'gps' => $this->gps]),
]),
```
...
```
<?php
    Modal::begin([
        'id' => 'show-map-modal',
        'header' => Html::tag('h3', Yii::t('app', 'Map')),
        'size' => Modal::SIZE_LARGE,
    ]);
```

```
$this->registerJs("
        $('#show-map-modal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var urlview = button.data('url') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-body').load(urlview);
})");
```

**Comment by Lordfef** [comment]
I have the same problem rendering the view via AJAX. Is there a way to solve this? 
Thank's

**Comment by Ratak** [comment]
The same problem, and as I see nobody gonna fix it)))

**Comment by reuhtte** [comment]
I think If this repo is dead I can create a new one and try to solve this.

The workaround that I applied was to include in the view

```
use dosamigos\google\maps\MapAsset;
MapAsset::register($this);

```
To have the correct Assets included.

And in the modal view I register the javascript to create the map object

```
<div id="test-map" style="height: 400px;"></div>
<?php

$this->registerJs("
    function initMap() {
        var myLatLng = {lat: {$coords[0]}, lng: {$coords[1]}};

        // Create a map object and specify the DOM element for display.
        var map = new google.maps.Map(document.getElementById('test-map'), {
            center: myLatLng,
            scrollwheel: false,
            zoom: 16
        });

        // Create a marker and set its position.
        var marker = new google.maps.Marker({
            map: map,
            position: myLatLng,
            title: 'Hello World!'
        });

        return map;
    }

");

$this->registerJs("
    var currentMap = initMap();
    setTimeout( function(){
        var center = currentMap.getCenter();
        google.maps.event.trigger(currentMap, 'resize');
        currentMap.setCenter(center);
    } , 400);
");

?>
```

**Comment by SerhiyNovoseletskiy** [comment]
I solved the problem like this:

`class Map extends \dosamigos\google\maps\Map
{
    private $_js = [];

    /**
     * @param $js
     *
     * @return $this
     */
    public function appendScript($js)
    {
        $this->_js[] = $js;

        return $this;
    }

    public function getJs()
    {
        $name = $this->getName();
        $width = strpos($this->width, "%") ? $this->width : $this->width . 'px';
        $height = strpos($this->height, "%") ? $this->height : $this->height . 'px';
        $containerId = ArrayHelper::getValue($this->containerOptions, 'id', $name . '-map-canvas');
        $overlaysJs = [];
        $js = [];
        foreach ($this->getOverlays() as $overlay) {
            /** @var ObjectAbstract $overlay */
            if (!ArrayHelper::keyExists("{$name}infoWindow", $this->getClosureScopedVariables()) &&
                method_exists($overlay, 'getIsInfoWindowShared')
                && $overlay->getIsInfoWindowShared()
            ) {
                $this->setClosureScopedVariable("{$name}infoWindow");
                $this->appendScript("{$name}infoWindow = new google.maps.InfoWindow();");
            }
            $overlay->options['map'] = new JsExpression($this->getName());
            $overlaysJs[] = $overlay->getJs();
        }
        $js[] = "(function(){";
        $js[] = $this->getClosureScopedVariablesScript();
        $js[] = "function initialize(){";
        $js[] = "var mapOptions = {$this->getEncodedOptions()};";
        $js[] = "var container = document.getElementById('{$containerId}');";
        $js[] = "container.style.width = '{$width}';";
        $js[] = "container.style.height = '{$height}';";
        $js[] = "var {$this->getName()} = new google.maps.Map(container, mapOptions);";
        $js = ArrayHelper::merge($js, $overlaysJs);
        foreach ($this->events as $event) {
            /** @var Event $event */
            $js[] = $event->getJs($name);
        }

        foreach ($this->getPlugins()->getInstalledPlugins() as $plugin) {
            /** @var \dosamigos\google\maps\PluginAbstract $plugin */
            $plugin->map = $this->getName();
            $js[] = $plugin->getJs($name);
        }

        $js = ArrayHelper::merge($js, $this->_js);
        $js[] = "};";
        //$js[] = "google.maps.event.addDomListener(window, 'load', initialize);";
        $js[] = "initialize();";
        $js[] = "})();";

        return implode("\n", $js);
    }
}`

**Comment by tonydspaniard** [comment]
It was fixed
