### ISSUE TITLE
Need ssl to connect

### ISSUE THREAD

**Issue by stivehu** [2amigos/yii2-google-maps-library#38]
After i set googleMapsApiKey param a got this message:
 ( [error_message] => Requests to this API must be over SSL. [results] => Array ( ) [status] => REQUEST_DENIED ) 

This is my patch:

# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- <html>GeocodingClient.php (<b>Today 10:04:15</b>)</html>
+++ <html><b>Current File</b></html>
@@ -52,7 +52,7 @@
      * @return string
      */
     public function getUrl() {
-        return 'http://maps.googleapis.com/maps/api/geocode/' . $this->format;
+        return 'https://maps.googleapis.com/maps/api/geocode/' . $this->format;
     }

     /**

**Comment by tonydspaniard** [comment]
this has been changed: https://github.com/2amigos/yii2-google-maps-library/blob/master/services/GeocodingClient.php#L57

**Comment by denisiodb** [comment]
The issue is no longer relevant for v1.0.
