### ISSUE TITLE
Create custome Icon

### ISSUE THREAD

**Issue by anushkanz** [2amigos/yii2-google-maps-library#44]
Hi help me to add custom icon, I want to change this icon every page. so try to create get and set functions in map page. Please help me that. Thanks

**Comment by kasoft** [comment]
If you mean the Marker Icons, you can change them this way

$marker = new Marker([
        'position' => $coord_audio,
        'icon' => '/pics/my_icon.png'
    ]);

**Comment by anushkanz** [comment]
Thanks, i will try today ......

**Comment by tonydspaniard** [comment]
I believe this actually work. Thanks @kasoft .
