### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by dudunegrinhu** [2amigos/yii2-google-maps-library#53]
I'm getting this error when I try to install via composer

Problem 1
    - Conclusion: don't install 2amigos/yii2-google-maps-library 1.0.0
    - Conclusion: don't install 2amigos/yii2-google-maps-library 0.1.2
    - Conclusion: don't install 2amigos/yii2-google-maps-library 0.1.1
    - Conclusion: remove guzzlehttp/streams 3.0.0
    - Installation request for 2amigos/yii2-google-maps-library * -> satisfiable by 2amigos/yii2-google-maps-library[0.1.0, 0.1.1, 0.1.2, 1.0.0].
    - Conclusion: don't install guzzlehttp/streams 3.0.0
    - 2amigos/yii2-google-maps-library 0.1.0 requires guzzlehttp/guzzle 4.* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3].
    - guzzlehttp/guzzle 4.0.0 requires guzzlehttp/streams 1.* -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.0.1 requires guzzlehttp/streams ~1.0 -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.0.2 requires guzzlehttp/streams ~1.0 -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.0 requires guzzlehttp/streams ~1.0 -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.1 requires guzzlehttp/streams ~1.0 -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.2 requires guzzlehttp/streams ~1.0 -> satisfiable by guzzlehttp/streams[1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.3 requires guzzlehttp/streams ~1.3 -> satisfiable by guzzlehttp/streams[1.3.0, 1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.4 requires guzzlehttp/streams ~1.4 -> satisfiable by guzzlehttp/streams[1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.5 requires guzzlehttp/streams ~1.4 -> satisfiable by guzzlehttp/streams[1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.6 requires guzzlehttp/streams ~1.4 -> satisfiable by guzzlehttp/streams[1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.7 requires guzzlehttp/streams ~1.4 -> satisfiable by guzzlehttp/streams[1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.1.8 requires guzzlehttp/streams ~1.4 -> satisfiable by guzzlehttp/streams[1.4.0, 1.5.0, 1.5.1].
    - guzzlehttp/guzzle 4.2.0 requires guzzlehttp/streams ~2.1 -> satisfiable by guzzlehttp/streams[2.1.0].
    - guzzlehttp/guzzle 4.2.1 requires guzzlehttp/streams ~2.1 -> satisfiable by guzzlehttp/streams[2.1.0].
    - guzzlehttp/guzzle 4.2.2 requires guzzlehttp/streams ~2.1 -> satisfiable by guzzlehttp/streams[2.1.0].
    - guzzlehttp/guzzle 4.2.3 requires guzzlehttp/streams ~2.1 -> satisfiable by guzzlehttp/streams[2.1.0].
    - Can only install one of: guzzlehttp/streams[1.0.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.1.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.2.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.3.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.4.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.5.0, 3.0.0].
    - Can only install one of: guzzlehttp/streams[1.5.1, 3.0.0].
    - Can only install one of: guzzlehttp/streams[2.1.0, 3.0.0].
    - Installation request for guzzlehttp/streams == 3.0.0.0 -> satisfiable by guzzlehttp/streams[3.0.0].

**Comment by DenisOgr** [comment]
Hi! I had catch same errors

**Comment by maxlen** [comment]
same error

**Comment by webmancer** [comment]
hi, I try to use your library and get errors with installation. Can you fix it? Thanks!

**Comment by tonydspaniard** [comment]
I'll have a look.

**Comment by maxlen** [comment]
It's helped https://getcomposer.org/doc/articles/troubleshooting.md#general

**Comment by newscloud** [comment]
Also having this problem.

**Comment by newscloud** [comment]
To be more clear for folks, this worked for me  - look at the end ...
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.7",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "2amigos/yii2-google-maps-library": "*",
        "2amigos/yii2-google-places-library": "*",
        "stichoza/google-translate-php": "~2.0",
        "2amigos/yii2-date-time-picker-widget": "*",
        "yiisoft/yii2-jui": "*",
        "cebe/yii2-gravatar": "*",
        "kartik-v/yii2-widget-fileinput": "*",
        "kartik-v/yii2-widget-switchinput": "*",
        "yiisoft/yii2-imagine": "*",
        "2amigos/yii2-resource-manager-component": "0.1.*",
        "yiisoft/yii2-authclient": "~2.0.0",
        "mailgun/mailgun-php": "~2.0",
        "guzzlehttp/guzzle":"6.2.0 as 4.2.3",
        "php-http/guzzle6-adapter":"1.0.0"
            },

composer update worked
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing php-http/message (v1.2.0)                                   
  - Removing php-http/message-factory (v1.0.2)
  - Removing clue/stream-filter (v1.3.0)
  - Removing guzzlehttp/streams (2.1.0)
  - Installing guzzlehttp/promises (1.1.0)
    Downloading: 100%         

  - Removing guzzlehttp/guzzle (4.2.3)
  - Installing guzzlehttp/guzzle (6.2.0)
    Downloading: 100%         

  - Installing php-http/guzzle6-adapter (v1.0.0)
    Downloading: 100%         

Writing lock file
Generating autoload files

**Comment by tonydspaniard** [comment]
added a patch to work with guzzle 6. Should be fine now.
