### ISSUE TITLE
Problem with polylines

### ISSUE THREAD

**Issue by NoOne777** [2amigos/yii2-google-maps-library#55]
Hi ! I have read the thread at https://github.com/2amigos/yii2-google-maps-library/issues/48.

However, I am still unable to render polylines. ;(

This is the code I'm trying:

Thank you ! ;)
```
$coord = new LatLng(['lat' => 35.8228518985860900, 'lng' => 9.0851454045645440]);

$map = new Map([
    'center' => $coord,
    'zoom' => 14,
    'width' => "100%",
]);

// Now lets write a polygon
$coords = [
    new LatLng(['lat' => 25.774252, 'lng' => -80.190262]),
    new LatLng(['lat' => 18.466465, 'lng' => -66.118292]),
    new LatLng(['lat' => 32.321384, 'lng' => -64.75737]),
];

$polyline = new Polyline([
    'path' => $coords,
]);

// Add it now to the map
$map->addOverlay($polyline); 
echo $map->display();
```

> PHP Recoverable Error – yii\base\ErrorException

Method yii\web\JsExpression::__toString() must return a string value
1. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/helpers/BaseJson.php at line 94
858687888990919293949596979899100101102103     * @param boolean $asArray whether to return objects in terms of associative arrays.
     * @return mixed the PHP data
     * @throws InvalidParamException if there is any decoding error
     */
    public static function decode($json, $asArray = true)
    {
        if (is_array($json)) {
            throw new InvalidParamException('Invalid JSON data.');
        }
        $decode = json_decode((string) $json, $asArray);
        static::handleJsonError(json_last_error());
 
        return $decode;
    }
 
    /**
     * Handles [[encode()]] and [[decode()]] errors by throwing exceptions with the respective error message.
     *
     * @param integer $lastError error code from [json_last_error()](http://php.net/manual/en/function.json-last-error.php).
2. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/helpers/BaseJson.php at line 94 – yii\base\ErrorHandler::handleError(4096, 'Method yii\web\JsExpression::__t...', '/Users/fcuccio/Eclipse/dronalyti...', 94, ...)
3. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/ObjectAbstract.php at line 155 – yii\helpers\BaseJson::decode(yii\web\JsExpression)
149150151152153154155156157158159160161                $parsed[] = $this->encode($child);
            }
            return $parsed;
        }
        try {
            // a value may contain a valid JSON string
            return Json::decode($value);
        } catch (InvalidParamException $e) {
 
        }
        return $value;
    }
 
4. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/ObjectAbstract.php at line 149 – dosamigos\google\maps\ObjectAbstract::encode(yii\web\JsExpression)
143144145146147148149150151152153154155            return new JsExpression($value->getJs());
        } elseif (is_bool($value)) {
            return new JsExpression(($value ? 'true' : 'false'));
        } elseif (is_array($value)) {
            $parsed = [];
            foreach ($value as $child) {
                $parsed[] = $this->encode($child);
            }
            return $parsed;
        }
        try {
            // a value may contain a valid JSON string
            return Json::decode($value);
5. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/ObjectAbstract.php at line 126 – dosamigos\google\maps\ObjectAbstract::encode([yii\web\JsExpression, yii\web\JsExpression, yii\web\JsExpression])
120121122123124125126127128129130131132        $options = [];
 
        foreach ($this->options as $key => $value) {
            if ($value === null) {
                continue;
            }
            $options[$key] = $this->encode($value);
 
        }
 
        return Json::encode($options);
    }
 
6. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/overlays/Polyline.php at line 62 – dosamigos\google\maps\ObjectAbstract::getEncodedOptions()
56575859606162636465666768     */
    public function getJs()
    {
 
        $js = $this->getInfoWindowJs();
 
        $js[] = "var {$this->getName()} = new google.maps.Polyline({$this->getEncodedOptions()});";
 
        foreach ($this->events as $event) {
            /** @var \dosamigos\google\maps\Event $event */
            $js[] = $event->getJs($this->getName());
        }
 
7. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/Map.php at line 405 – dosamigos\google\maps\overlays\Polyline::getJs()
399400401402403404405406407408409410411                && $overlay->getIsInfoWindowShared()
            ) {
                $this->setClosureScopedVariable("{$name}infoWindow");
                $this->appendScript("{$name}infoWindow = new google.maps.InfoWindow();");
            }
            $overlay->options['map'] = new JsExpression($this->getName());
            $overlaysJs[] = $overlay->getJs();
        }
        $js[] = "(function(){";
        $js[] = $this->getClosureScopedVariablesScript();
        $js[] = "function initialize(){";
        $js[] = "var mapOptions = {$this->getEncodedOptions()};";
        $js[] = "var container = document.getElementById('{$containerId}');";
8. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/Map.php at line 369 – dosamigos\google\maps\Map::getJs()
363364365366367368369370371372373374375     */
    public function registerClientScript($position = View::POS_END)
    {
        $view = Yii::$app->getView();
        MapAsset::register($view);
 
        $view->registerJs($this->getJs(), $position);
    }
 
    /**
     * @param $js
     *
     * @return $this
9. in /Users/fcuccio/Eclipse/dronalytics/vendor/2amigos/yii2-google-maps-library/Map.php at line 342 – dosamigos\google\maps\Map::registerClientScript()
336337338339340341342343344345346347348 
    /**
     * @return string
     */
    public function display()
    {
        $this->registerClientScript();
 
        return $this->renderContainer();
    }
 
    /**
     * @return string
10. in /Users/fcuccio/Eclipse/dronalytics/frontend/views/flight/overview.php at line 196 – dosamigos\google\maps\Map::display()
190191192193194195196197198199200201202 
// Append its resulting script
$map->appendScript($bikeLayer->getJs());
*/
 
// Display the map -finally :)
echo $map->display();
 
 
 
?>
 
 
11. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/View.php at line 325 – require('/Users/fcuccio/Eclipse/dronalyti...')
12. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/Users/fcuccio/Eclipse/dronalyti...', ['model' => common\models\Flight])
13. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/Users/fcuccio/Eclipse/dronalyti...', ['model' => common\models\Flight], frontend\controllers\FlightController)
14. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('overview', ['model' => common\models\Flight], frontend\controllers\FlightController)
15. in /Users/fcuccio/Eclipse/dronalytics/frontend/controllers/FlightController.php at line 230 – yii\base\Controller::render('overview', ['model' => common\models\Flight])
224225226227228229230231232233    }
 
    public function actionOverview($id)
    {
        return $this->render('overview', [
            'model' => $this->findModel($id),
        ]);
    }
 
}
16. frontend\controllers\FlightController::actionOverview('1')
17. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([frontend\controllers\FlightController, 'actionOverview'], ['1'])
18. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['id' => '1'])
19. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('overview', ['id' => '1'])
20. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('flight/overview', ['id' => '1'])
21. in /Users/fcuccio/Eclipse/dronalytics/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
22. in /Users/fcuccio/Eclipse/dronalytics/frontend/web/index.php at line 18 – yii\base\Application::run()
12131415161718    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
$application = new yii\web\Application($config);
$application->run();
 $_GET = [
    'id' => '1',
];

$_COOKIE = [
    'PHPSESSID' => 'icvbs6347u684f7qqj1mp1hv45',
    '_csrf' => '92e7d9a5761e65ec2de9e8b8eafa6693ebd2199cbf9edaa411851672b1bbb1efa:2:{i:0;s:5:"_csrf";i:1;s:32:"Sx_sR-6Grz_SDDvo8NR1TzAulMH1eRjt";}',
    '_identity' => 'bc622de821adbb71d1c4c5b775eac1428ce799b610e8bcfad808fbe08851f0ada:2:{i:0;s:9:"_identity";i:1;s:46:"[1,"TeCZhJlwJSH_PZYgs6ozb28cebEYnYh2",2592000]";}',
];

**Comment by NoOne777** [comment]
Apparently I didn't read issue https://github.com/2amigos/yii2-google-maps-library/issues/48 very well. It's all in there.

**Comment by stasionok** [comment]
I got same error (Method yii\web\JsExpression::__toString() must return a string value)
I am compare Polylines with Marker and I change in PolyLineOptions
I just remove setPath  function
After that i saw polyline on map!
May be need to check path elements for LatLng.

**Comment by alpo008** [comment]
@stasionok 
Thanks. Your solution with setPath was really helpful.
