### ISSUE TITLE
GeocodeClient reverse method failed on send LatLng object

### ISSUE THREAD

**Issue by hrmohseni** [2amigos/yii2-google-maps-library#65]
GeocodeClient reverse method failed on send LatLng object the fix is below:

`services\GeocodingClient.php`
line:90
`$params['latlng'] = $coord->__toString();`

It seams this will fix problem:
[Fix 'latlng' param pull request](https://github.com/2amigos/yii2-google-maps-library/pull/63)

**Comment by tonydspaniard** [comment]
merged
