### ISSUE TITLE
error javascript

### ISSUE THREAD

**Issue by McNamara10** [2amigos/yii2-google-maps-library#66]
I have installed this extension with composer!, but start application on display this error Ups! Ada sesuatu yang salah.
Laman ini tidak memuat Google Maps dengan benar. Lihat konsol JavaScript untuk mengetahui detail teknisnya. in the console javascript error"Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key"

**Comment by tonydspaniard** [comment]
Have you created your very own google api key?

**Comment by McNamara10** [comment]
yes, now it's ok
