### ISSUE TITLE
Plugin assets bundle

### ISSUE THREAD

**Issue by makroxyz** [2amigos/yii2-google-maps-library#71]
Have a look at Map.php row 364.
I think this method should call $this->getPlugins()->registerAssetBundles... isn't it?

```php
public function registerClientScript($position = View::POS_END)
{
    $view = Yii::$app->getView();
    MapAsset::register($view);
    $this->getPlugins()->registerAssetBundles($view); // <---- IS THIS MISSING??
    $view->registerJs($this->getJs(), $position);
}
```

**Comment by tonydspaniard** [comment]
Not really, MapAsset is the one doing it on the line above.

**Comment by makroxyz** [comment]
mmmm.... where?
nobody call PluginManager::registerAssetBundles

**Comment by tonydspaniard** [comment]
You know? Please, forgive me. I thought this was leaflet extension (on my mobile). You are right! Good catch.

**Comment by makroxyz** [comment]
So is it the right place to put that call?
Anyway... my pleasure to help if I can!
