### ISSUE TITLE
how to show map full width,.??

### ISSUE THREAD

**Issue by hariadi04** [2amigos/yii2-google-maps-library#72]
![image](https://cloud.githubusercontent.com/assets/10745517/22864427/44da0f0c-f18c-11e6-8109-e9d785430239.png)

**Comment by hariadi04** [comment]
solve.
i found it. 

thx,.

**Comment by mannabua** [comment]
hariadi04 what did you do?

**Comment by hariadi04** [comment]
edit map.php
![image](https://cloud.githubusercontent.com/assets/10745517/23109963/7484964c-f758-11e6-81bb-ed3dfa7b9c40.png)

**Comment by mannabua** [comment]
Thanks mate!

**Comment by McNamara10** [comment]
but it's possible setting 100% of width?

**Comment by Suaz** [comment]
this works for me
 $map = new Map([
                    'center' => $coord,
                    'zoom' => 17,
                    'width' => '100%',
                    'height' => '300',
                ]);

**Comment by nicolasecolman** [comment]
@McNamara10 You have to use '100%' instead of a number. 

@hariadi04 If you do so, you will have to modify that file every time you install de package with a package manager. You have to pass the with parameter when you create a Map instance (as Suaz commented before).

**Comment by imtiazmahbub** [comment]
You can also set 
```
public $width = 'auto';
``` 
instead of `100%`
