### ISSUE TITLE
ReferenceError: Can't find variable: google

### ISSUE THREAD

**Issue by contreras2004** [2amigos/yii2-google-maps-library#82]
I istalled the library and I used this simple code to make a simple map: 

`<?
                        $coord = new LatLng(['lat' => 39.720089311812094, 'lng' => 2.91165944519042]);
                        $map = new Map([
                            'center' => $coord,
                            'zoom' => 14,
                        ]);

                        // Display the map -finally :)
                        echo $map->display();
?>`

But I get that error code. Any ideas of what can it be?
Im loading the map in a modal window, it works on other views

**Comment by contreras2004** [comment]
Never mind, I just found out I had to register for map assets on the main view 
`use dosamigos\google\maps\MapAsset;
MapAsset::register($this);`

**Comment by deshario** [comment]
Hello @contreras2004 
It really works on issue #119  when i tried to load map at first time ... But In console i have little error ..
![errorrrrrrrrrrrrr](https://user-images.githubusercontent.com/11426727/41901356-e4189d98-795a-11e8-8a53-dcff3d7b40ec.PNG)
Did you know how to fix that. Thanks

**Comment by deshario** [comment]
Hello @contreras2004
It really works on issue #119 Thanks
