### ISSUE TITLE
Geometry library and isLocationOnEdge()

### ISSUE THREAD

**Issue by contreras2004** [2amigos/yii2-google-maps-library#86]
Is there any way I can integrate this plugin with the geometry library provided by Google Maps? I need to detect if some points are in the best route between 2 points returned by DirectionsRequest().

I'm a little lost here

**Comment by tonydspaniard** [comment]
You need to modify the AssetBundle: https://github.com/2amigos/yii2-google-maps-library#configuration add `'libraries' => 'geometry'` to it.

**Comment by contreras2004** [comment]
Wow man, thanks for the ultra quick response but unfortunately I'm still a little bit lost.

Let me explain. I tried first drawing the polyline using the directionService like so: 

First I Geocode the origine and end location for the path and after that I draw the polyline on the map but after the line is successfully drawn on the map, how can I have a reference to it so I can perform the geometry function on it?

`/*CONFIGURANDO EL MAPA*/
$coord = new LatLng(['lat' => 39.720089311812094, 'lng' => 2.91165944519042]);
$map = new Map([
    'center' => $coord,
    'zoom' => 14,
]);

// lets use the directions renderer
$home = new LatLng(['lat' => 39.720991014764536, 'lng' => 2.911801719665541]);
$school = new LatLng(['lat' => 39.719456079114956, 'lng' => 2.8979293346405166]);
$santo_domingo = new LatLng(['lat' => 39.72118906848983, 'lng' => 2.907628202438368]);

//veamos si funciona el geocoding:
$origen = "Los Militares 4915";
//$geo = new GeocodingClient();

$geo_coding_client = new GeocodingClient();
$lookup_response = $geo_coding_client->lookup([
    'address' => $origen,
    'region' => "Chile",
]);

// The lookup response can return more results or even return errors if the location can't be found,
// the following will set the first found result in $lat and $lng variables
$lat = isset($lookup_response->results[0]->geometry->location->lat) ? $lookup_response->results[0]->geometry->location->lat : null;
$lng = isset($lookup_response->results[0]->geometry->location->lng) ? $lookup_response->results[0]->geometry->location->lng : null;

if (!is_null($lat) && !is_null($lng)) {
	$origen_LatLng = new LatLng([
		'lat' => $lat,
        'lng' => $lng,
	]);
}

$destino = "Via Roja 9215, Lo Curro";

$geo_coding_client = new GeocodingClient();
$lookup_response = $geo_coding_client->lookup([
    'address' => $destino,
    'region' => "Chile",
]);

// The lookup response can return more results or even return errors if the location can't be found,
// the following will set the first found result in $lat and $lng variables
$lat = isset($lookup_response->results[0]->geometry->location->lat) ? $lookup_response->results[0]->geometry->location->lat : null;
$lng = isset($lookup_response->results[0]->geometry->location->lng) ? $lookup_response->results[0]->geometry->location->lng : null;

if (!is_null($lat) && !is_null($lng)) {
	$destino_LatLng = new LatLng([
		'lat' => $lat,
        'lng' => $lng,
	]);
}

$directionsRequest = new DirectionsRequest([
    'origin' => $origen_LatLng,
    'destination' => $destino_LatLng,
    'travelMode' => TravelMode::DRIVING
]);

// Lets configure the polyline that renders the direction
$polylineOptions = new PolylineOptions([
    'strokeColor' => 'red',
    'draggable' => false
]);

// Now the renderer
$directionsRenderer = new DirectionsRenderer([
    'map' => $map->getName(),
    'polylineOptions' => $polylineOptions
]);

// Finally the directions service
$directionsService = new DirectionsService([
    'directionsRenderer' => $directionsRenderer,
    'directionsRequest' => $directionsRequest
]);

$map->display();
//the map displays the polyline but I dont have any reference to it so I can't perform geometry functions
`

**Comment by tonydspaniard** [comment]
All the objects do have the option for you to set  up its name. Like for example, the DirectionsService: https://github.com/2amigos/yii2-google-maps-library/blob/master/services/DirectionsService.php#L94 

Once you setup its name, you could access to it by using the `Map::appendScript` function https://github.com/2amigos/yii2-google-maps-library/blob/master/Map.php#L377 

For example, if you named the direction services like `ds`, the script will render `var ds=`, so on your appended script, you could reference the service as: `$map->appendScript('ds.whatever');` Hope it helps

**Comment by tonydspaniard** [comment]
Check here... it will also give you a clear hint: https://github.com/2amigos/yii2-google-maps-library/blob/master/services/DirectionsService.php#L87
