### ISSUE TITLE
Custom Icon Marker

### ISSUE THREAD

**Issue by rusli-nasir** [2amigos/yii2-google-maps-library#90]
help me.
I add custom icon like this

**$point = new Point([
        'x' => 0,'y' => 0
    ]);
	$size = new Size([
        'height' => 50,'width' => 50
    ]);
	$icon = new Icon([
        'url' => Url::to('@web/img/icon/wifi.png'),
        'origin' => $point,
        'anchor' => $point,
        'scaledSize' => $size
    ]);**

but I have error like this
**Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message '"x" and "y" cannot be null.' 
in xxx\vendor\2amigos\yii2-google-maps-library\Point.php:44**

**Comment by tonydspaniard** [comment]
The problem is that you setup the point to be at 0,0. It must have a value > 0.
