### ISSUE TITLE
Making the map fit the full width of the screen is not supported by Map::getMarkersFittingZoom()

### ISSUE THREAD

**Issue by dbd5** [2amigos/yii2-google-maps-library#92]
@tonydspaniard ,

The function Map::getMarkersFittingZoom() doesn't support percentages so the suggestion provided in #72 isn't great. Is there a better way to make the map fit the full width of the screen without using percentages considering that we know nothing of the user device width?

Thanks

**Comment by imtiazmahbub** [comment]
You can also set 
```
public $width = 'auto';
``` 
instead of `100%`

**Comment by tonydspaniard** [comment]
@db5 what I would do on that case is creating a js function that will always get the current width of viewport and then set the width of the map accordingly on window.resize events.

**Comment by dbd5** [comment]
@tonydspaniard - Brilliant idea!

Will experiment with this and revert, thanks

**Comment by tonydspaniard** [comment]
@dbd5 let us know how it went!
