### ISSUE TITLE
Compile error in PHP 7.2

### ISSUE THREAD

**Issue by acerix** [2amigos/yii2-google-maps-library#94]
> PHP Compile Error – yii\base\ErrorException
> 
> Cannot use yii\base\Object as Object because 'Object' is a special class name
> 1. in /vendor/2amigos/yii2-google-maps-library/ObjectAbstract.php at line 10

**Comment by acerix** [comment]
This issue is back after this commit: https://github.com/2amigos/yii2-google-maps-library/commit/739e54af01db445b5b77150fa715931214430bcc

Please fix for PHP 7.2 or document if it's not supported.

**Comment by Cheaterz** [comment]
Still not working for PHP 7.2
